version: '3'
services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RAILS_ENV: ""
        BUNDLE_WITHOUT: ""
        BUNDLE_DEPLOYMENT: ""
        FROZEN_LOCKFILE: ""
        NO_DOCUMENT: ""
        ENVIRONMENT: development
    command: sleep infinity
    volumes:
      - ./:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
