services:
  api:
    build: api
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command:
      - ./bin/rails
      - server
      - -b
      - 0.0.0.0
    environment:
      RAILS_ENV: development
      BUNDLE_WITHOUT: ""
      TZ: Asia/Tokyo
    working_dir: /rails
    volumes:
      - type: bind
        source: ./api
        target: /rails
      - type: bind
        source: ./schema
        target: /schema

    # TODO: Gemfile が bind mount されてしまっていると動かないのでなんとかしたい
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: api/Gemfile

  front:
    build: front
    ports:
      - 3001:3000
    command:
      - /bin/sh
      - -c
      - 'yarn && yarn dev'
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: development
      NEXT_PUBLIC_API_HOST: http://localhost:3000
    working_dir: /app
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: volume
        source: front-node_modules
        target: /app/node_modules

  doc:
    image: redocly/redoc
    ports:
      - 8012:80
    volumes:
      - ./schema/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      SPEC_URL: openapi.yaml

volumes:
  front-node_modules:
