
require:
  # - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Rails:
  Enabled: true

# Layout/EmptyLineAfterGuardClause:
#   Enabled: false
Layout/EmptyLines:
  Enabled: false
# Layout/LineLength:
#   Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
# Metrics/CyclomaticComplexity:
#   Max: 9
# Metrics/MethodLength:
#   Max: 13
# Metrics/PerceivedComplexity:
#   Max: 9
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
# Style/IfUnlessModifier:
#   Enabled: false
# # Style/PerlBackrefs:
# #   Enabled: false
#
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
# Style/SpecialGlobalVars:
#   Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
