env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
  sourceType: 'module'
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
root: true
plugins:
  - '@typescript-eslint'
  - react
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
rules:
  '@typescript-eslint/ban-types':
    - error
    - extendDefaults: true
      types:
        '{}': false
  '@typescript-eslint/explicit-module-boundary-types': 'off'
