inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - "log/**/*"
    - 'tmp/**/*'

# 文字列のダブルクォートチェック
Style/StringLiterals:
  EnforcedStyle: double_quotes

# 数字の桁区切りは不要
Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 26

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 35

Rails/HttpStatus:
  Enabled: false