inherit_from: .rubocop_todo.yml

require: rubocop-rails # 必須

AllCops:
  # 除外するディレクトリ（自動生成されるファイル）
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Rakefile'

  NewCops: enable
