Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

# 参考サイト: https://zenn.dev/seiya2020/articles/af041663ab11c7
Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
