version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    # wsl用 ホストの UID と GID を環境変数から設定
    # UID_GID="$(id -u):$(id -g)" docker-compose up
    user: "${UID_GID}"
    depends_on:
      - db
volumes:
  postgres_volume: