import Head from "next/head";
import { Form } from "../components/ui/form";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.header}>
          <h1>
            電気代から
            <br />
            かんたんシミュレーション
          </h1>
          <p>
            検針票を用意しなくてもOK
            <br />
            いくらおトクになるのか今すぐわかります！
          </p>
        </header>
        <Form />
      </main>
    </>
  );
}
