inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.0.6
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/FindEach:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'config/routes.rb'
    - 'test/**/*'

Metrics/ClassLength:
  CountComments: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/ModuleLength:
  CountComments: false

Naming/FileName:
  Exclude:
    - 'Gemfile'

Naming/MethodParameterName:
  AllowedNames: [e]

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/BlockComments:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true