東京電力エナジーパートナー:
  plan_name:
    "従量電灯B"
  basic_rates:
    10: 286.00
    15: 429.00
    20: 572.00
    30: 858.00
    40: 1144.00
    50: 1430.00
    60: 1716.00
  usage_rates:
    - range: [1, 120]
      rate: 19.88
    - range: [121, 300]
      rate: 26.48
    - range: [301, "inf"]
      rate: 30.57

LOOPでんき:
  plan_name:
    "おうちプラン"
  basic_rates:
    10: 0.00
    15: 0.00
    20: 0.00
    30: 0.00
    40: 0.00
    50: 0.00
    60: 0.00
  usage_rates:
    - range: [1, "inf"]
      rate: 26.40

東京ガス株式会社:
  plan_name:
    "ずっとも電気1"
  basic_rates:
    30: 858.00
    40: 1144.00
    50: 1430.00
    60: 1716.00
  usage_rates:
    - range: [1, 140]
      rate: 23.67
    - range: [141, 350]
      rate: 23.88
    - range: [351, "inf"]
      rate: 26.41

JXTGでんき(旧myでんき):
  plan_name:
    "従量電灯Bたっぷりプラン"
  basic_rates:
    30: 858.00
    40: 1144.00
    50: 1430.00
    60: 1716.80
  usage_rates:
    - range: [1, 120]
      rate: 19.88
    - range: [121, 300]
      rate: 26.48
    - range: [301, 600]
      rate: 25.08
    - range: [601, "inf"]
      rate: 26.15
