provider_name: 'JXTGでんき'
plan_name: '従量電灯Bたっぷりプラン'
basic_charges:
  30: 858
  40: 1144
  50: 1430
  60: 1716.8
usage_charges:
  condition_1:
    limit: 120
    rate: 19.88
  condition_2:
    limit: 300
    rate: 26.48
  condition_3:
    limit: 600
    rate: 25.08
  condition_4:
    limit: +.inf
    rate: 26.15
