provider_name: '東京電力エナジーパートナー'
plan_name: '従量電灯B'
basic_charges:
  10: 286
  15: 429
  20: 572
  30: 858
  40: 1144
  50: 1430
  60: 1716
usage_charges:
  condition_1:
    limit: 120
    rate: 19.88
  condition_2:
    limit: 300
    rate: 26.48
  condition_3:
    limit: +.inf
    rate: 30.57
