default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_PRODUCTION"] %>
