---
openapi: 3.0.3
info:
  title: Challenge API
  version: 1.0.0
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths:
  "/api/electricity/calculate":
    post:
      summary: 電気料金を計算する
      tags:
      - 電気料金
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amperage:
                  type: integer
                electricity_usage_kwh:
                  type: integer
              required:
              - amperage
              - electricity_usage_kwh
            example:
              amperage: 10
              electricity_usage_kwh: 1
      responses:
        '200':
          description: 正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        provider:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                          required:
                          - id
                          - name
                        plan:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            price:
                              type: integer
                          required:
                          - id
                          - name
                          - price
                      required:
                      - provider
                      - plan
                required:
                - data
              example:
                data:
                - provider:
                    id: 5
                    name: 東京電力エナジーパートナー
                  plan:
                    id: 5
                    name: 従量電灯B
                    price: 305
                - provider:
                    id: 5
                    name: 東京電力エナジーパートナー
                  plan:
                    id: 6
                    name: スタンダードS
                    price: 341
                - provider:
                    id: 7
                    name: Looopでんき
                  plan:
                    id: 8
                    name: おうちプラン
                    price: 28
        '400':
          description: パラメータ不正
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        message:
                          type: string
                      required:
                      - field
                      - message
                required:
                - message
                - details
              example:
                message: リクエストパラメーターが正しくありません。
                details:
                - field: amperage
                  message: 10/15/20/30/40/50/60のいずれかを指定してください。
                - field: electricity_usage_kwh
                  message: 整数を指定してください。
