shared:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 16
  username: root
  password: p@ssw0rd
  host: 127.0.0.1

development:
  database: mydb

test:
  database: mydb

production:
  database: mydb
