name: Delete PR Folder on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  delete-pr-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Delete PR folder
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          FOLDER_PATH="pr/$PR_NUMBER"
          if [ -d "$FOLDER_PATH" ]; then
            rm -rf $FOLDER_PATH
            echo "Folder $FOLDER_PATH deleted"
          else
            echo "Folder $FOLDER_PATH does not exist"
          fi

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Remove folder for PR ${{ github.event.pull_request.number }}" || exit 0
          git push
