name: Sample Deploy for GitHub Pages

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace entire content of next.config.js for-github-workflows.next.config.js
        run: |
          cat frontend_challenge_2/challenges/k-taro56/for-github-workflows.next.config.js > frontend_challenge_2/challenges/k-taro56/next.config.js

      - name: Set enviroments
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          DEPLOY_PATH=pr/${{ github.event.pull_request.number }}/${{ github.event.pull_request.head.sha }}
          echo "DEPLOY_PATH=$DEPLOY_PATH" >> $GITHUB_ENV
          DEPLOY_URL=https://${{ github.repository_owner }}.github.io/$REPO_NAME/$DEPLOY_PATH
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Set up pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Set up pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend_challenge_2/challenges/k-taro56

      - name: Build
        env:
          REPO_NAME: ${{ secrets.REPO_NAME }}/${{ env.DEPLOY_PATH }}
        run: |
          pnpm build
        working-directory: frontend_challenge_2/challenges/k-taro56

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend_challenge_2/challenges/k-taro56/out
          destination_dir: ${{ env.DEPLOY_PATH }}
          keep_files: true

      - name: Comment PR with Deploy URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const deploy_url = process.env.DEPLOY_URL;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `🚀 Deploy preview ready: [${deploy_url}](${deploy_url})`
            });
