name: Build and Deploy

on:
  push:
    branches: master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace entire content of next.config.js for-github-workflows.next.config.js
        run: |
          cat frontend_challenge_2/challenges/k-taro56/for-github-workflows.next.config.js > frontend_challenge_2/challenges/k-taro56/next.config.js

      - name: Set repository name
        id: extract_repo
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Set up pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Set up pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend_challenge_2/challenges/k-taro56

      - name: Build
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          pnpm build
        working-directory: frontend_challenge_2/challenges/k-taro56

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend_challenge_2/challenges/k-taro56/out
          keep_files: true
