name: Run test

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Set up pnpm
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Set up pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend_challenge_2/challenges/k-taro56

      - name: Run tests with coverage
        run: pnpm test:ci
        working-directory: frontend_challenge_2/challenges/k-taro56

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          use_oidc: true
          files: ./frontend_challenge_2/challenges/k-taro56/coverage/lcov.info
          fail_ci_if_error: true
